version: '3.8'
services:
  server:
    container_name: league_bot_server
    build:
      context: .
      dockerfile: ./Dockerfile
#    image: docker.pkg.github.com/coryball/backend-template/template-app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    env_file: env/dev.env
  postgres:
    container_name: league_bot_database
    image: postgres:13.2
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file: env/dev.env
    volumes:
      - ./.docker/data/:/data/postgres
      - ./.docker/psql_scripts/:/docker-entrypoint-initdb.d/