version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
#    image: docker.pkg.github.com/coryball/backend-template/template-server
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    env_file: env/dev.env
  postgres:
    container_name: backend_template_database
    image: postgres:13.2
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_PORT: $DATABASE_PORT
      PGDATA: /data/postgres
    env_file: env/dev.env
    volumes:
      - ./.docker/data/:/data/postgres
      - ./.docker/psql_scripts/:/docker-entrypoint-initdb.d/
