version: '3.8'
services:
  server:
    container_name: league_bot_server
    build:
      context: .
      dockerfile: ./Dockerfile
    image: docker.pkg.github.com/coryball/discord-bot-league/discord-bot-league
    depends_on:
      - postgres
    env_file: env/prod.env
  postgres:
    container_name: league_bot_database
    image: postgres:13.2
    expose:
      - "5432"
    env_file: env/prod.env
    volumes:
      - ./.docker/data/:/data/postgres
      - ./.docker/psql_scripts/:/docker-entrypoint-initdb.d/